apiVersion: v1
kind: Pod
metadata:
  name: myapp-frontend
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: nginx-conatiner
      env:
        - name: ENVIRONMENT
          value: Production