apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
#    - ReadWriteMany
#    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath: # You can replace this with third party solution
    path: /home/fensomer/k8s-vols
    type: Directory