apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-role-binding
subjects:
  - kind: User
    named: cluster-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: ClusterRole
    named: cluster-admin
    apiGroup: rbac.authorization.k8s.io