apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-binding
subjects:
  - kind: User
    named: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    named: dev
    apiGroup: rbac.authorization.k8s.io