apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
    - name: pod-nginx
      image: nginx
#  imagePullSecrets:
#    - name: regcred  # Optional pull secret for private registries