apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemonset
spec:
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: monitoring-agent
          image: nginx
  selector:
    matchLabels:
      type: monitoring-agent