apiVersion: v1
kind: Pod
metadata:
  name: pod-with-svc-acc
spec:
  containers:
    - name: pod-with-svc-acc
      image: busybox
      command: ["sleep","1800"]
  serviceAccountName: pod-svc-acc
  # automountServiceAccountToken: false # Comment in the above if you do not wish for token to be mounted within pod.