apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-CKA
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-conatiner
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end