apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "create", "update", "delete"]
    #resourceNames: ["red"]
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create", "update", "delete"]